from django.db import models
from clientes.models import Cliente, TerminosPago
from inventario.models import Producto


# Create your models here.
class DevolucionClte(models.Model):
    devolucion_clte_id = models.AutoField(primary_key=True)
    nro_devolucion_clte = models.CharField(max_length=10)
    cliente = models.ForeignKey(Cliente)
    clte_direccion1 = models.CharField(max_length=80)
    clte_direccion2 = models.CharField(max_length=80)
    clte_direccion3 = models.CharField(max_length=80)
    clte_direccion4 = models.CharField(max_length=80)
    registro_tributario = models.CharField(max_length=80)
    enviar = models.CharField(max_length=80)
    enviar_direccion1 = models.CharField(max_length=80)
    enviar_direccion2 = models.CharField(max_length=80)
    enviar_direccion3 = models.CharField(max_length=80)
    enviar_direccion4 = models.CharField(max_length=80)
    refer_cliente = models.CharField(max_length=20)
    tipo_envio = models.CharField(max_length=80)
    vendedor_id = models.IntegerField()
    termino = models.ForeignKey(TerminosPago)
    fecha_emision = models.CharField(max_length=10)
    hora = models.CharField(max_length=16)
    fecha_vcmto = models.CharField(max_length=10)
    computador = models.TextField()
    moneda = models.IntegerField()
    subtotal = models.DecimalField(max_digits=18, decimal_places=4)
    total = models.DecimalField(max_digits=18, decimal_places=4)
    impuesto_pciento = models.DecimalField(max_digits=18, decimal_places=4)
    impuesto_monto = models.DecimalField(max_digits=18, decimal_places=4)
    dscto_pciento = models.DecimalField(max_digits=18, decimal_places=4)
    dscto_monto = models.DecimalField(max_digits=18, decimal_places=4)
    dscto_parcial_monto = models.DecimalField(max_digits=18, decimal_places=4)
    impuesto2_pciento = models.DecimalField(max_digits=18, decimal_places=4)
    impuesto2_monto = models.DecimalField(max_digits=18, decimal_places=4)
    miscelaneos = models.DecimalField(max_digits=18, decimal_places=4)
    miscelaneos_pciento = models.DecimalField(max_digits=18, decimal_places=4)
    comentario = models.TextField()
    comentario_detalle = models.TextField(db_column='comentario_Detalle')  # Field name made lowercase.
    tipo_cambio = models.DecimalField(max_digits=18, decimal_places=4)
    notas = models.TextField()
    impto_en_precio = models.IntegerField()
    tipo_documento = models.CharField(max_length=40)
    retefuente_pciento = models.DecimalField(max_digits=18, decimal_places=4)
    retefuente_monto = models.DecimalField(max_digits=18, decimal_places=4)
    reteiva_pciento = models.DecimalField(max_digits=18, decimal_places=4)
    reteiva_monto = models.DecimalField(max_digits=18, decimal_places=4)
    reteica_pciento = models.DecimalField(max_digits=18, decimal_places=4)
    reteica_monto = models.DecimalField(max_digits=18, decimal_places=4)
    monto_base = models.DecimalField(max_digits=18, decimal_places=4)
    nro_estimado = models.CharField(max_length=10)
    actualizado = models.DateTimeField()
    ncf = models.CharField(max_length=10)
    en_anexo = models.CharField(max_length=2)
    campo1 = models.CharField(max_length=30)
    campo2 = models.DecimalField(max_digits=18, decimal_places=4)
    campo3 = models.CharField(max_length=20)
    asiento_id = models.IntegerField()
    docs_cc_id = models.IntegerField()
    kardex_id = models.IntegerField()
    pagos = models.DecimalField(max_digits=18, decimal_places=4)
    anulada = models.IntegerField()
    causa_anulacion = models.TextField()

    class Meta:
        db_table = 'devolucion_clte'


class DevolucionClteDetalle(models.Model):
    detalle_id = models.AutoField(primary_key=True)
    devolucion_clte = models.ForeignKey(DevolucionClte)
    fecha_emision = models.CharField(max_length=10)
    cliente_id = models.IntegerField()
    producto = models.ForeignKey(Producto)
    bodega_id = models.IntegerField()
    cantidad = models.DecimalField(max_digits=18, decimal_places=4)
    recibido = models.DecimalField(max_digits=18, decimal_places=4)
    unidad_id = models.IntegerField()
    precio_devolucion_clte = models.DecimalField(max_digits=18, decimal_places=4)
    impto_pciento = models.DecimalField(max_digits=18, decimal_places=4)
    impto_monto = models.DecimalField(max_digits=18, decimal_places=4)
    descto_pciento = models.DecimalField(max_digits=18, decimal_places=4)
    descto_monto = models.DecimalField(max_digits=18, decimal_places=4)
    impto2_pciento = models.DecimalField(max_digits=18, decimal_places=4)
    impto2_monto = models.DecimalField(max_digits=18, decimal_places=4)
    comentario = models.TextField()
    tipo_cambio = models.DecimalField(max_digits=18, decimal_places=4)
    moneda = models.IntegerField()
    anulada = models.IntegerField()
    costo_producto = models.DecimalField(max_digits=18, decimal_places=4)

    class Meta:
        db_table = 'devolucion_clte_detalle'
