from django.db import models
# from os.path import basename
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from clientes.models import Cliente
from config.models import *

from vendedor.models import *
from inventario.models import *
from reunion.models import *
from datetime import datetime    

from django.core.exceptions import ValidationError



# Create your models here.
class CotizacionProforma(models.Model):
    codigo = models.CharField(max_length=250, blank=True)
    fecha = models.DateField(blank=True, null=True)
    cliente = models.ForeignKey(Cliente, blank=True, null=True)
    descripcion = models.CharField(max_length=250, blank=True)
    detalle = models.TextField(blank=True)
    cantidad = models.IntegerField(blank=True, null=True)
    largo = models.CharField(max_length=250, blank=True)
    fondo = models.CharField(max_length=250, blank=True)
    alto = models.CharField(max_length=250, blank=True)
    madera = models.NullBooleanField()
    vidrio = models.NullBooleanField()
    hierro = models.NullBooleanField()
    marmol = models.NullBooleanField()
    enchape = models.NullBooleanField()
    enchape_detalle = models.CharField(max_length=250, blank=True)
    tallado = models.NullBooleanField()
    tallado_detalle = models.CharField(max_length=250, blank=True)
    tono = models.CharField(max_length=250, blank=True)
    retractil = models.NullBooleanField()
    panorama = models.NullBooleanField()
    corredizo = models.NullBooleanField()
    oleo = models.NullBooleanField()
    conchaperla = models.NullBooleanField()
    tela_almacen = models.NullBooleanField()
    tela_cliente = models.NullBooleanField()
    agarraderas = models.CharField(max_length=250, blank=True)
    imagen = models.ImageField(null=True,blank=True,upload_to = "imagenes/proforma/")
    guia = models.IntegerField(blank=True, null=True)
    adicional = models.NullBooleanField()
    fechapedido = models.DateField(blank=True, null=True)
    tipo = models.CharField(max_length=250, blank=True)
    estado = models.IntegerField(blank=True, null=True)
    tipo_mue = models.IntegerField(blank=True, null=True)
    doc = models.IntegerField(blank=True, null=True)
    mate = models.NullBooleanField()
    semimate = models.NullBooleanField()
    brillante = models.NullBooleanField()
    pulido = models.NullBooleanField()
    aluminio = models.NullBooleanField()
    acero = models.NullBooleanField()
    abrillantado = models.NullBooleanField()
    pintado = models.NullBooleanField()
    satinado = models.NullBooleanField()
    fechacotizacion = models.NullBooleanField()
    engrampe = models.NullBooleanField()
    impulso = models.NullBooleanField()
    poroabierto = models.NullBooleanField()
    ingreso = models.IntegerField(blank=True, null=True)
    cantaux = models.IntegerField(blank=True, null=True)
    created_by = models.CharField(max_length=255, blank=True)
    updated_by = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    vendedor = models.ForeignKey(Vendedor, blank=True, null=True)
    tiempo_respuesta = models.CharField(max_length=255, blank=True)
    fuera_ciudad = models.BooleanField()
    observacion = models.TextField(blank=True)
    forma_pago = models.ForeignKey(FormaPago, blank=True, null=True)
    ambiente_id = models.IntegerField(blank=True, null=True)
    maqueteado_proforma = models.BooleanField()
    terminado_maqueteado_proforma = models.BooleanField()
    reunion_codigo = models.CharField(max_length=255, blank=True)
    reunion = models.ForeignKey(Reunion, blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    direccion_entrega = models.CharField(max_length=255, blank=True)
    iva = models.FloatField(blank=True, null=True)
    subtotal = models.FloatField(blank=True, null=True)
    descuento = models.FloatField(blank=True, null=True)
    porcentaje_descuento = models.FloatField(blank=True, null=True)
    aprobada = models.NullBooleanField()
    anulada = models.NullBooleanField()
    tipo_lugar = models.ForeignKey(TipoLugar, blank=True, null=True)
    cotizacion_finalizada = models.BooleanField()
    puntos_venta = models.ForeignKey(PuntosVenta,default=1, blank=True, null=True)
    abreviatura_codigo = models.CharField(max_length=10, blank=True, null=True)
    hierro_proforma = models.BooleanField()
    porcentaje_iva = models.FloatField(blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'cotizacion_proforma'

class CotizacionProformaDetalle(models.Model):
    cotizacion_proforma = models.ForeignKey(CotizacionProforma, blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    nombre = models.CharField(max_length=255, blank=True)
    producto = models.ForeignKey(Producto, blank=True, null=True)
    cantidad = models.FloatField(blank=True, null=True)
    precio_compra = models.FloatField(blank=True, null=True)
    descto_pciento = models.FloatField(blank=True, null=True)
    medida = models.CharField(max_length=255, blank=True)
    imagen =  models.ImageField(null=True,blank=True,upload_to = "imagenes/cotizacion_proforma_detalle/")
    observaciones = models.CharField(max_length=255, blank=True)
    created_by = models.CharField(max_length=255, blank=True)
    updated_by = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    detalle = models.TextField(blank=True)
    ambiente = models.ForeignKey(Ambiente, blank=True, null=True)
    reparacion = models.NullBooleanField()
    almacen = models.NullBooleanField()
    largo = models.CharField(max_length=255, blank=True)
    fondo = models.CharField(max_length=255, blank=True)
    alto = models.CharField(max_length=255, blank=True)
    producto_creado = models.ForeignKey(Producto, related_name='producto_creado')
    nombre_producto_creado = models.CharField(max_length=255, blank=True)
    producto_general = models.ForeignKey(ProductoGeneral, blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'cotizacion_proforma_detalle'



class Proforma(models.Model):
    def validate_numero(value):
        if not value.isdigit():
            raise ValidationError("Solo se permiten numeros.")
        
    codigo = models.CharField(max_length=250, blank=True)
    fecha = models.DateField(default=datetime.now,blank=True, null=True)
    cliente = models.ForeignKey(Cliente, blank=True, null=True)
    descripcion = models.CharField(max_length=250, blank=True)
    detalle = models.TextField(blank=True)
    cantidad = models.IntegerField(blank=True, null=True)
    largo = models.CharField(max_length=250, blank=True)
    fondo = models.CharField(max_length=250, blank=True)
    alto = models.CharField(max_length=250, blank=True)
    madera = models.NullBooleanField()
    vidrio = models.NullBooleanField()
    hierro = models.NullBooleanField()
    marmol = models.NullBooleanField()
    enchape = models.NullBooleanField()
    enchape_detalle = models.CharField(max_length=250, blank=True)
    tallado = models.NullBooleanField()
    tallado_detalle = models.CharField(max_length=250, blank=True)
    tono = models.CharField(max_length=250, blank=True)
    retractil = models.NullBooleanField()
    panorama = models.NullBooleanField()
    corredizo = models.NullBooleanField()
    oleo = models.NullBooleanField()
    conchaperla = models.NullBooleanField()
    tela_almacen = models.NullBooleanField()
    tela_cliente = models.NullBooleanField()
    agarraderas = models.CharField(max_length=250, blank=True)
    imagen = models.ImageField(null=True,blank=True,upload_to = "imagenes/proforma/")
    guia = models.IntegerField(blank=True, null=True)
    adicional = models.NullBooleanField()
    fechapedido = models.DateField(default=datetime.now,blank=True, null=True)
    tipo = models.CharField(max_length=250, blank=True)
    estado = models.ForeignKey(EstadosPro, db_column='estado', blank=True, null=True)
    tipo_mue = models.ForeignKey(TipoMueb, db_column='tipo_mue', blank=True, null=True)
    doc = models.IntegerField(blank=True, null=True)
    mate = models.NullBooleanField()
    semimate = models.NullBooleanField()
    brillante = models.NullBooleanField()
    pulido = models.NullBooleanField()
    aluminio = models.NullBooleanField()
    acero = models.NullBooleanField()
    abrillantado = models.NullBooleanField()
    pintado = models.NullBooleanField()
    satinado = models.NullBooleanField()
    fechacotizacion = models.NullBooleanField()
    engrampe = models.NullBooleanField()
    impulso = models.NullBooleanField()
    poroabierto = models.NullBooleanField()
    ingreso = models.IntegerField(blank=True, null=True)
    cantaux = models.IntegerField(blank=True, null=True)
    created_by = models.CharField(max_length=255, blank=True)
    updated_by = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    ambiente = models.CharField(max_length=250, blank=True)
    fuera_ciudad = models.BooleanField()
    tiempo_respuesta = models.CharField(max_length=250, blank=True)
    vendedor = models.ForeignKey(Vendedor, blank=True, null=True)
    observacion= models.TextField(blank=True)
    forma_pago =models.ForeignKey(FormaPago, blank=True, null=True)
    ambiente = models.ForeignKey(Ambiente, blank=True, null=True)
    maqueteado_proforma = models.BooleanField()
    terminado_maqueteado_proforma = models.BooleanField()
    reunion_codigo = models.CharField(max_length=250, blank=True)
    reunion = models.ForeignKey(Reunion, blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    direccion_entrega = models.CharField(max_length=250, blank=True)
    iva = models.FloatField(blank=True, null=True)
    subtotal = models.FloatField(blank=True, null=True)
    descuento = models.FloatField(blank=True, null=True)
    porcentaje_descuento = models.FloatField(blank=True, null=True)
    aprobada = models.BooleanField(blank=True)
    anulada = models.BooleanField(blank=True)
    tipo_lugar = models.ForeignKey(TipoLugar,default=1)
    puntos_venta = models.ForeignKey(PuntosVenta,default=1)
    abreviatura_codigo = models.CharField(max_length=10, blank=True)
    hierro_proforma = models.BooleanField()
    porcentaje_iva = models.FloatField(blank=True, null=True)
    referido_por = models.ForeignKey(Vendedor, related_name='referido_por', blank=True, null=True)
    cotizacion_proforma = models.ForeignKey(CotizacionProforma, blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'proforma'

    



class ProformaDetalle(models.Model):
    proforma = models.ForeignKey(Proforma, blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    nombre = models.CharField(max_length=255, blank=True)
    producto = models.ForeignKey(Producto, blank=True, null=True)
    cantidad = models.FloatField(blank=True, null=True)
    precio_compra = models.FloatField(blank=True, null=True)
    descto_pciento = models.FloatField(blank=True, null=True)
    medida = models.CharField(max_length=255, blank=True)
    imagen = models.ImageField(null=True,blank=True,upload_to = "imagenes/proforma_detalle/")
    observaciones = models.CharField(max_length=255, blank=True)
    # observaciones = models.CharField(max_length=255, blank=True)
    created_by = models.CharField(max_length=255, blank=True)
    updated_by = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    detalle = models.TextField(blank=True)
    ambiente = models.ForeignKey(Ambiente, blank=True, null=True)
    reparacion = models.BooleanField(default=False)
    almacen = models.BooleanField(default=False)
    largo = models.CharField(max_length=255, blank=True)
    fondo = models.CharField(max_length=255, blank=True)
    alto = models.CharField(max_length=255, blank=True)
    codigo_produccion= models.CharField(max_length=255, blank=True)
    no_producir = models.BooleanField(default=False)
    class Meta:
        db_table = 'proforma_detalle'

class ImagenesCotizacionProforma(models.Model):
    descripcion = models.TextField(blank=True)
    cotizacion_proforma_detalle = models.ForeignKey(CotizacionProformaDetalle, blank=True, null=True)
    imagen = models.ImageField(null=True,blank=True,upload_to = "imagenes/cotizacion_proforma_detalle/")
    created_by = models.CharField(max_length=255, blank=True)
    updated_by = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    class Meta:
        db_table = 'imagenes_cotizacion_proforma'


class ProformaFactura(models.Model):
    codigo = models.CharField(max_length=250, blank=True)
    fecha = models.DateField(blank=True, null=True)
    cliente = models.ForeignKey(Cliente, blank=True, null=True)
    descripcion = models.CharField(max_length=250, blank=True)
    detalle = models.TextField(blank=True)
    cantidad = models.IntegerField(blank=True, null=True)
    largo = models.CharField(max_length=250, blank=True)
    fondo = models.CharField(max_length=250, blank=True)
    alto = models.CharField(max_length=250, blank=True)
    madera = models.NullBooleanField()
    vidrio = models.NullBooleanField()
    hierro = models.NullBooleanField()
    marmol = models.NullBooleanField()
    enchape = models.NullBooleanField()
    enchape_detalle = models.CharField(max_length=250, blank=True)
    tallado = models.NullBooleanField()
    tallado_detalle = models.CharField(max_length=250, blank=True)
    tono = models.CharField(max_length=250, blank=True)
    retractil = models.NullBooleanField()
    panorama = models.NullBooleanField()
    corredizo = models.NullBooleanField()
    oleo = models.NullBooleanField()
    conchaperla = models.NullBooleanField()
    tela_almacen = models.NullBooleanField()
    tela_cliente = models.NullBooleanField()
    agarraderas = models.CharField(max_length=250, blank=True)
    imagen = models.ImageField(null=True,blank=True,upload_to = "imagenes/proforma/")
    guia = models.IntegerField(blank=True, null=True)
    adicional = models.NullBooleanField()
    fechapedido = models.DateField(default=datetime.now,blank=True, null=True)
    tipo = models.CharField(max_length=250, blank=True)
    estado = models.ForeignKey(EstadosPro, db_column='estado', blank=True, null=True)
    tipo_mue = models.ForeignKey(TipoMueb, db_column='tipo_mue', blank=True, null=True)
    doc = models.IntegerField(blank=True, null=True)
    mate = models.NullBooleanField()
    semimate = models.NullBooleanField()
    brillante = models.NullBooleanField()
    pulido = models.NullBooleanField()
    aluminio = models.NullBooleanField()
    acero = models.NullBooleanField()
    abrillantado = models.NullBooleanField()
    pintado = models.NullBooleanField()
    satinado = models.NullBooleanField()
    fechacotizacion = models.NullBooleanField()
    engrampe = models.NullBooleanField()
    impulso = models.NullBooleanField()
    poroabierto = models.NullBooleanField()
    ingreso = models.IntegerField(blank=True, null=True)
    cantaux = models.IntegerField(blank=True, null=True)
    created_by = models.CharField(max_length=255, blank=True)
    updated_by = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    ambiente = models.CharField(max_length=250, blank=True)
    fuera_ciudad = models.BooleanField()
    tiempo_respuesta = models.CharField(max_length=250, blank=True)
    vendedor = models.ForeignKey(Vendedor, blank=True, null=True)
    observacion= models.TextField(blank=True)
    forma_pago =models.ForeignKey(FormaPago, blank=True, null=True)
    ambiente = models.ForeignKey(Ambiente, blank=True, null=True)
    maqueteado_proforma = models.BooleanField()
    terminado_maqueteado_proforma = models.BooleanField()
    reunion_codigo = models.CharField(max_length=250, blank=True)
    reunion = models.ForeignKey(Reunion, blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    direccion_entrega = models.CharField(max_length=250, blank=True)
    iva = models.FloatField(blank=True, null=True)
    subtotal = models.FloatField(blank=True, null=True)
    descuento = models.FloatField(blank=True, null=True)
    porcentaje_descuento = models.FloatField(blank=True, null=True)
    aprobada = models.BooleanField()
    anulada = models.BooleanField()
    tipo_lugar = models.ForeignKey(TipoLugar,default=1)
    puntos_venta = models.ForeignKey(PuntosVenta,default=1)
    abreviatura_codigo = models.CharField(max_length=10, blank=True)
    hierro_proforma = models.BooleanField()
    porcentaje_iva = models.FloatField(blank=True, null=True)
    proforma = models.ForeignKey(Proforma, blank=True, null=True)
    proforma_codigo = models.CharField(max_length=255, blank=True)
    class Meta:
        managed = False
        db_table = 'proforma_factura'


class ProformaDetalleFactura(models.Model):
    proforma_factura = models.ForeignKey(ProformaFactura, blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    nombre = models.CharField(max_length=255, blank=True)
    producto = models.ForeignKey(Producto, blank=True, null=True)
    cantidad = models.FloatField(blank=True, null=True)
    precio_compra = models.FloatField(blank=True, null=True)
    descto_pciento = models.FloatField(blank=True, null=True)
    medida = models.CharField(max_length=255, blank=True)
    imagen = models.ImageField(null=True,blank=True,upload_to = "imagenes/proforma_detalle/")
    observaciones = models.CharField(max_length=255, blank=True)
    created_by = models.CharField(max_length=255, blank=True)
    updated_by = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    detalle = models.TextField(blank=True)
    ambiente = models.ForeignKey(Ambiente, blank=True, null=True)
    reparacion = models.BooleanField(default=False)
    almacen = models.BooleanField(default=False)
    largo = models.CharField(max_length=255, blank=True)
    fondo = models.CharField(max_length=255, blank=True)
    alto = models.CharField(max_length=255, blank=True)
    codigo_produccion= models.CharField(max_length=255, blank=True)
    class Meta:
        managed = False
        db_table = 'proforma_detalle_factura'
