
from django.conf.urls import patterns, include, url
from django.views.defaults import *
from .views import *

urlpatterns = patterns('',

    url(
        r'^proforma/$',
        ProformaListView.as_view(),
        name='proforma-list',
    ),

    url(
        r'^consultarproforma/$',
        'proforma.views.ConsultaProformaListView',
        name='proforma-consultar-list',
    ),
    url(
        r'^proforma_render/$',
        ProformaRenderListView.as_view(),
        name='proforma-render-list',
    ),

   url(
        r'^proforma/nuevo$',
  'proforma.views.ProformaCreateView',
        name='proforma-create',
    ),
   url(
        r'^proforma/(?P<pk>\d+)/crear$',
    'proforma.views.ProformaCreateReunionView',
        name='proforma-create-reunion',
    ),
   url(
        r'^proforma/seguimiento_reuniones$',
    'proforma.views.SeguimientoReuniones',
        name='proforma-seguimiento',
    ),
   url(
         r'^proforma/(?P<pk>\d+)/editar/$',
         ProformaUpdateView.as_view(),
         name='proforma-update',
    ),
   url(
         r'^proforma/(?P<pk>\d+)/subirrender/$',
         ProformaRenderView.as_view(),
         name='proforma-subir-render',
    ),
   url(
        r'^proforma/(?P<pk>\d+)/detalle/$',
        ProformaDetailView.as_view(),
        name='proforma-detail',
    ),
    url(
        r'^proforma/eliminar/$',
        'proforma.views.ProformaEliminarView',
        name='proforma-delete',
    ),
    url(
        r'^proforma/(?P<pk>\d+)/eliminar/$',
        'proforma.views.ProformaEliminarByPkView',
        name='proforma-delete-pk',
    ),
    url(
        r'^proforma/guardar/$',
        'proforma.views.misProformaGuardar',
        name='configuracion-proforma-guardar',
    ),
    url(
        r'^proformaAprobar/$',
        'proforma.views.ProformaListAprobarView',
        name='proforma-list-aprobada',
    ),

    url(
        r'^proforma/(?P<pk>\d+)/aprobar/$',
        'proforma.views.ProformaAprobarByPkView',
        name='aprobar-proforma',
    ),
    url(
        r'^proforma/(?P<pk>\d+)/anular/$',
        'proforma.views.ProformaAnularByPkView',
        name='anular-proforma',
    ),
    url(
        r'^cotizarproforma/$',
        'proforma.views.CotizacionProformaListView',
        name='cotizacionproforma-list',
    ),
    url(
        r'^cotizarproforma/nuevo$',
    'proforma.views.CotizacionProformaCreateView',
        name='cotizacionproforma-create',
    ),
    url(
         r'^cotizarproforma/(?P<pk>\d+)/editar/$',
         CotizacionProformaUpdateView.as_view(),
         name='cotizacionproforma-update',
    ),
    url(
        r'^cotizarproforma/cotizar/$',
        'proforma.views.CotizacionProformaListCotizarView',
        name='cotizacionproforma-listcotizar',
    ),
     url(
         r'^cotizarproforma/(?P<pk>\d+)/cotizar/$',
         CotizacionProformaUpdateCotizarView.as_view(),
         name='cotizacionproformacotizar-update',
    ),
      url(
         r'^cotizarproforma/(?P<pk>\d+)/subirrender/$',
         CotizacionProformaRenderView.as_view(),
         name='cotizacionproforma-subir-render',
    ),
    url(
        r'^cotizarproforma_render/$',
        CotizacionProformaRenderListView.as_view(),
        name='cotizacionproforma-render-list',
    ),
    url(
        r'^cotizarproforma/(?P<pk>\d+)/subirimagen$',
    'proforma.views.SubirImagenesView',
        name='cotizacionproforma-subirimagen',
    ),
     url(
         r'^cotizarproforma/(?P<pk>\d+)/ver/$',
         CotizacionProformaVerView.as_view(),
         name='cotizacion-ver',
    ),
     url(
        r'^cotizarproforma/(?P<pk>\d+)/subirimagenver$',
    'proforma.views.SubirImagenesVerView',
        name='cotizacionproforma-subirimagenver',
    ),
    url(
        r'^cotizarproforma/(?P<pk>\d+)/crearproforma$',
    'proforma.views.CotizacionProformaCreateProformaView',
        name='cotizacionproforma-create-proforma',
    ),
    url(
        r'^imprimir/(?P<pk>\d+)/$',
        'proforma.views.index',
        name='proforma-imprimir',
    ),
    url(
        r'^historico/$',
        'proforma.views.HistoricoListView',
        name='proforma-historico-list',
    ),
    url(
         r'^proforma/(?P<pk>\d+)/editarhistorico/$',
         ProformaHistoricoUpdateView.as_view(),
         name='proforma-historico-update',
    ),
    url(
        r'^obtenerAbreviatura/$',
        'proforma.views.obtenerAbreviatura',
        name='proforma-obtener-abreviatura',
    ),
    url(
        r'^cotizacionimprimir/(?P<pk>\d+)/$',
        'proforma.views.imprimirCotizacion',
        name='cotizacionproforma-imprimir',
    ),
    url(
        r'^obtenerAbreviaturaCotizacion/$',
        'proforma.views.obtenerAbreviaturaCotizacion',
        name='proforma-obtener-abreviatura-cotizacion',
    ),

    url(
        r'^mostrar_imagen/$',
        'proforma.views.MostrarImagenView',
        name='mostrar_imagen_proforma',
    ),
     url(
        r'^eliminar_imagen/$',
        'proforma.views.ImagenEliminarView',
        name='eliminar_imagen',
    ),
     url(
        r'^proformafactura/nuevo$',
  'proforma.views.ProformaFacturaCreateView',
        name='proforma-factura-create',
    ),

     url(
        r'^proformafactura/(?P<pk>\d+)/crearproforma/$',
        'proforma.views.ProformaFacturaCrearProformaView',
        name='crear-proforma-proforma-factura',
    ),

      url(
        r'^proformafactura/$',
  'proforma.views.ProformaFacturaListView',
        name='proforma-factura-list',
    ),

      url(
        r'^proformaFacturaAprobar/$',
        'proforma.views.ProformaFacturaListAprobarView',
        name='proforma-factura-list-aprobada',
    ),

    url(
        r'^proformaFactura/(?P<pk>\d+)/aprobar/$',
        'proforma.views.ProformaFacturaAprobarByPkView',
        name='aprobar-proforma-factura',
    ),
      url(
        r'^proformaFactura/(?P<pk>\d+)/anular/$',
        'proforma.views.ProformaFacturaAnularByPkView',
        name='anular-proforma-factura',
    ),

       url(
        r'^obtenerDetalleProformaFactura/$',
  'proforma.views.obtenerDetalleProformaFactura',
        name='obtener-proforma-factura',
    ),

        url(
        r'^obtenerProformaFacturaFacturacion/$',
  'proforma.views.obtenerProformaFacturaFacturacion',
        name='obtener-proforma-factura-facturacion',
    ),

         url(
         r'^proformaFactura/(?P<pk>\d+)/editar/$',
         ProformaFacturaUpdateView.as_view(),
         name='proforma-factura-update',
    ),
url(
        r'^proforma/(?P<pk>\d+)/copiarproforma$',
    'proforma.views.CopiarProformaView',
        name='copiar-proforma',
    ),
                       url(
                           r'^ProformaEliminarDetalleView/$',
                           'proforma.views.ProformaEliminarDetalleView',
                           name='eliminar-proforma-detalle',
                       ),

url(
                           r'^CotizacionProformaEliminarDetalleView/$',
                           'proforma.views.CotizacionProformaEliminarDetalleView',
                           name='eliminar-cotizacion-proforma-detalle',
                       ),
)
