from django.db import models
from proveedores.models import Proveedor
from inventario.models import Producto,Bodega,Unidades
from datetime import datetime    

# Create your models here.
class OrdenCompra(models.Model):
    compra_id = models.AutoField(primary_key=True)
    nro_compra = models.IntegerField()
    proveedor = models.ForeignKey(Proveedor)
    supl_direccion1 = models.CharField(max_length=255)
    supl_direccion2 = models.CharField(max_length=255)
    supl_direccion3 = models.CharField(max_length=255)
    supl_direccion4 = models.CharField(max_length=255)
    registro_tributario = models.CharField(max_length=255)
    enviar = models.NullBooleanField()
    enviar_direccion1 = models.CharField(max_length=255)
    enviar_direccion2 = models.CharField(max_length=255)
    enviar_direccion3 = models.CharField(max_length=255)
    enviar_direccion4 = models.CharField(max_length=255)
    nro_fact_proveedor = models.CharField(max_length=255,blank=True)
    tipo_envio = models.CharField(max_length=255)
    vendedor = models.CharField(max_length=255)
    terminos_id = models.IntegerField()
    fecha = models.DateTimeField(default=datetime.now,blank=True)
    hora = models.DateTimeField()
    fecha_vcmto = models.DateTimeField()
    pagos = models.CharField(max_length=255)
    computador = models.CharField(max_length=255)
    moneda = models.CharField(max_length=255)
    subtotal =models.FloatField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    impuesto_pciento =models.FloatField(blank=True, null=True)
    impuesto_monto =models.FloatField(blank=True, null=True)
    dscto_pciento = models.FloatField(blank=True, null=True)
    dscto_monto = models.FloatField(blank=True, null=True)
    dscto_parcial_monto = models.DecimalField(max_digits=8, decimal_places=2)
    impuesto2_pciento = models.FloatField()
    impuesto2_monto = models.DecimalField(max_digits=8, decimal_places=2)
    miscelaneos = models.CharField(max_length=255)
    miscelaneos_pciento = models.CharField(max_length=255)
    comentario = models.CharField(max_length=255,blank=True)
    comentario_detalle = models.CharField(max_length=255)
    tipo_cambio = models.CharField(max_length=255)
    notas = models.CharField(max_length=255,blank=True)
    asiento_id = models.IntegerField()
    docs_cp_id = models.IntegerField()
    kardex_id = models.IntegerField()
    recibida = models.CharField(max_length=255)
    impto_en_precio = models.FloatField()
    tipo_compra = models.CharField(max_length=255)
    retefuente_pciento = models.FloatField()
    retefuente_monto = models.DecimalField(max_digits=8, decimal_places=2)
    reteiva_pciento = models.FloatField()
    reteiva_monto = models.DecimalField(max_digits=8, decimal_places=2)
    reteica_pciento = models.FloatField()
    reteica_monto = models.DecimalField(max_digits=8, decimal_places=2)
    monto_base = models.FloatField()
    tipo_registracion = models.CharField(max_length=255)
    anulado = models.NullBooleanField()
    compra_cancelada = models.NullBooleanField()
    actualizado = models.NullBooleanField()
    ncf = models.CharField(max_length=255)
    created_by = models.CharField(max_length=255,blank=True)
    updated_by = models.CharField(max_length=255,blank=True)
    created_at = models.DateTimeField(blank=True)
    updated_at = models.DateTimeField(blank=True)
    aprobada = models.BooleanField()
    bodega = models.ForeignKey(Bodega)
    facturada = models.BooleanField(default=False)
    subtotal_descuento=models.FloatField(blank=True, null=True)
    class Meta:
        db_table = 'orden_compra'
class ComprasDetalle(models.Model):
    compras_detalle_id = models.AutoField(primary_key=True)
    compra_id = models.IntegerField(blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    proveedor = models.ForeignKey(Proveedor,blank=True,)
    producto = models.ForeignKey(Producto)
    bodega = models.ForeignKey(Bodega,blank=True,)
    cantidad = models.FloatField(blank=True, null=True)
    recibido = models.BooleanField(default=False)
    unidad = models.ForeignKey(Unidades, blank=True, null=True)
    precio_compra = models.FloatField(blank=True, null=True)
    impto_pciento = models.FloatField(blank=True, null=True)
    impto_monto = models.FloatField(blank=True, null=True)
    descto_pciento = models.FloatField(blank=True, null=True)
    descto_monto = models.FloatField(blank=True, null=True)
    impto2_pciento = models.FloatField(blank=True, null=True)
    impto2_monto = models.FloatField(blank=True, null=True)
    comentario = models.CharField(max_length=255, blank=True)
    tipo_cambio = models.CharField(max_length=255, blank=True)
    moneda = models.CharField(max_length=255, blank=True)
    total = models.FloatField(blank=True, null=True)
    created_by = models.CharField(max_length=255, blank=True)
    updated_by = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    tipo_precio = models.CharField(max_length=255,blank=True)
    class Meta:
        db_table = 'compras_detalle'

class ComprasLocales(models.Model):
    codigo = models.CharField(max_length=255, blank=True)
    orden_compra = models.ForeignKey(OrdenCompra, blank=True, null=True)
    proveedor = models.ForeignKey(Proveedor, blank=True, null=True)
    nro_fact_proveedor = models.CharField(max_length=255)
    terminos_id = models.IntegerField(blank=True, null=True)
    fecha = models.DateTimeField(default=datetime.now,blank=True, null=True)
    subtotal = models.FloatField(blank=True, null=True)
    subtotal_descuento = models.FloatField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    dscto_pciento = models.FloatField(blank=True, null=True)
    dscto_monto = models.FloatField(blank=True, null=True)
    iva = models.FloatField(blank=True, null=True)
    iva_pciento = models.FloatField(blank=True, null=True)
    comentario = models.CharField(max_length=255, blank=True)
    kardex_id = models.IntegerField(blank=True, null=True)
    recibida = models.CharField(max_length=255, blank=True)
    impto_en_precio = models.FloatField(blank=True, null=True)
    retefuente_pciento = models.FloatField(blank=True, null=True)
    retefuente_monto = models.FloatField(blank=True, null=True)
    reteiva_pciento = models.FloatField(blank=True, null=True)
    reteiva_monto = models.FloatField(blank=True, null=True)
    reteica_pciento = models.FloatField(blank=True, null=True)
    reteica_monto = models.FloatField(blank=True, null=True)
    monto_base = models.FloatField(blank=True, null=True)
    anulado = models.NullBooleanField()
    compra_cancelada = models.NullBooleanField()
    actualizado = models.NullBooleanField()
    created_by = models.CharField(max_length=255, blank=True)
    updated_by = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    class Meta:
        db_table = 'compras_locales'

