from django.conf.urls import patterns, include, url
from django.views.defaults import *
from .views import *

urlpatterns = patterns('',

                       url(
                           r'^modificarEmpresa/$',
                           'config.views.modificarEmpresa',
                           name='modificar-empresa-list',
                       ),
                       url(
                           r'^obtenerSecuencial/$',
                           'config.views.obtenerSecuencial',
                           name='obtener-secuencia',
                       ),
                       url(
                           r'^obtenerParametro/$',
                           'config.views.obtenerParametro',
                           name='obtener-parametro',
                       ),
                       url(
                           r'^obtenerReunion/$',
                           'config.views.obtenerReunion',
                           name='obtener-reunion',
                       ),
                       url(
                           r'^obtenerProforma/$',
                           'config.views.obtenerProforma',
                           name='obtener-proforma',
                       ),
                       url(
                           r'^obtenerOrdenCompra/$',
                           'config.views.obtenerOrdenCompra',
                           name='obtener-orden-compra',
                       ),
                       url(
                           r'^obtenerCompraDetalle/$',
                           'config.views.obtenerCompraDetalle',
                           name='obtener-compradetalle',
                       ),
                       url(
                           r'^obtenerDetalleProforma/$',
                           'config.views.obtenerDetalleProforma',
                           name='obtener-detalleproforma',
                       ),
                       url(
                           r'^obtenerDetalleCompra/$',
                           'config.views.obtenerDetalleCompra',
                           name='obtener-detalle-compra',
                       ),
                       url(
                           r'^eliminarDetalleCompra/$',
                           'config.views.eliminarDetalleCompra',
                           name='eliminar-detalle-compra',
                       ),
                       url(
                           r'^recibirDetalleCompra/$',
                           'config.views.recibirDetalleCompra',
                           name='recibir-detalle-compra',
                       ),

                       url(
                           r'^obtenerDetalleAjuste/$',
                           'config.views.obtenerDetalleAjuste',
                           name='obtener-detalle-ajuste',
                       ),

                       url(
                           r'^areas/$',
                           'config.views.AreasListView',
                           name='areas-list',
                       ),

                       url(
                           r'^areas/nuevo$',
                           AreasCreateView.as_view(),

                           name='areas-create',
                       ),
                       url(
                           r'^areas/(?P<pk>\d+)/editar/$',
                           AreasUpdateView.as_view(),
                           name='areas-update',
                       ),
                       url(
                           r'^areas/(?P<pk>\d+)/detalle/$',
                           AreasDetailView.as_view(),
                           name='areas-detail',
                       ),
                       url(
                           r'^areas/eliminar/$',
                           'config.views.AreasEliminarView',
                           name='areas-delete',
                       ),
                       url(
                           r'^areas/(?P<pk>\d+)/eliminar/$',
                           'config.views.AreasEliminarByPkView',
                           name='areas-delete-pk',
                       ),
                       url(
                           r'^areas/guardar/$',
                           'config.views.misAreasGuardar',
                           name='configuracion-areas-guardar',
                       ),
                       url(
                           r'^vehiculo/$',
                           VehiculoListView.as_view(),
                           name='vehiculo-list',
                       ),

                       url(
                           r'^vehiculo/nuevo$',
                           VehiculoCreateView.as_view(),
                           name='vehiculo-create',
                       ),
                       url(
                           r'^vehiculo/(?P<pk>\d+)/editar/$',
                           VehiculoUpdateView.as_view(),
                           name='vehiculo-update',
                       ),
                       url(
                           r'^vehiculo/(?P<pk>\d+)/detalle/$',
                           VehiculoDetailView.as_view(),
                           name='vehiculo-detail',
                       ),
                       url(
                           r'^vehiculo/eliminar/$',
                           'config.views.VehiculoEliminarView',
                           name='vehiculo-delete',
                       ),
                       url(
                           r'^vehiculo/(?P<pk>\d+)/eliminar/$',
                           'config.views.VehiculoEliminarByPkView',
                           name='vehiculo-delete-pk',
                       ),
                       url(
                           r'^vehiculo/guardar/$',
                           'config.views.misVehiculoGuardar',
                           name='configuracion-vehiculo-guardar',
                       ),

                       url(
                           r'^estadospro/$',
                           EstadosProListView.as_view(),
                           name='estadospro-list',
                       ),

                       url(
                           r'^estadospro/nuevo$',
                           EstadosProCreateView.as_view(),
                           name='estadospro-create',
                       ),
                       url(
                           r'^estadospro/(?P<pk>\d+)/editar/$',
                           EstadosProUpdateView.as_view(),
                           name='estadospro-update',
                       ),
                       url(
                           r'^estadospro/(?P<pk>\d+)/detalle/$',
                           EstadosProDetailView.as_view(),
                           name='estadospro-detail',
                       ),
                       url(
                           r'^estadospro/eliminar/$',
                           'config.views.EstadosProEliminarView',
                           name='estadospro-delete',
                       ),
                       url(
                           r'^estadospro/(?P<pk>\d+)/eliminar/$',
                           'config.views.EstadosProEliminarByPkView',
                           name='estadospro-delete-pk',
                       ),
                       url(
                           r'^estadospro/guardar/$',
                           'config.views.misEstadosProGuardar',
                           name='configuracion-estadospro-guardar',
                       ),
                       url(
                           r'^tipomueb/$',
                           TipoMuebListView.as_view(),
                           name='tipomueb-list',
                       ),

                       url(
                           r'^tipomueb/nuevo$',
                           TipoMuebCreateView.as_view(),
                           name='tipomueb-create',
                       ),
                       url(
                           r'^tipomueb/(?P<pk>\d+)/editar/$',
                           TipoMuebUpdateView.as_view(),
                           name='tipomueb-update',
                       ),
                       url(
                           r'^tipomueb/(?P<pk>\d+)/detalle/$',
                           TipoMuebDetailView.as_view(),
                           name='tipomueb-detail',
                       ),
                       url(
                           r'^tipomueb/eliminar/$',
                           'config.views.TipoMuebEliminarView',
                           name='tipomueb-delete',
                       ),
                       url(
                           r'^tipomueb/(?P<pk>\d+)/eliminar/$',
                           'config.views.TipoMuebEliminarByPkView',
                           name='tipomueb-delete-pk',
                       ),
                       url(
                           r'^tipomueb/guardar/$',
                           'config.views.misTipoMuebGuardar',
                           name='configuracion-tipomueb-guardar',
                       ),

                       url(
                           r'^secuenciales/$',
                           'config.views.SecuencialesListView',
                           name='secuenciales-list',
                       ),

                       url(
                           r'^secuenciales/nuevo$',
                           'config.views.SecuencialesCreateView',
                           name='secuenciales-create',
                       ),
                       url(
                           r'^secuenciales/(?P<pk>\d+)/editar/$',
                           SecuencialesUpdateView.as_view(),
                           name='secuenciales-update',
                       ),
                       url(
                           r'^secuenciales/(?P<pk>\d+)/detalle/$',
                           SecuencialesDetailView.as_view(),
                           name='secuenciales-detail',
                       ),
                       url(
                           r'^secuenciales/eliminar/$',
                           'config.views.SecuencialesEliminarView',
                           name='secuenciales-delete',
                       ),
                       url(
                           r'^secuenciales/(?P<pk>\d+)/eliminar/$',
                           'config.views.SecuencialesEliminarByPkView',
                           name='secuenciales-delete-pk',
                       ),

                       url(
                           r'^menu/$',
                           MenuListView.as_view(),
                           name='menu-list',
                       ),

                       url(
                           r'^menu/nuevo$',
                           'config.views.MenuCreateView',
                           name='menu-create',
                       ),
                       url(
                           r'^menu/(?P<pk>\d+)/editar/$',
                           MenuUpdateView.as_view(),
                           name='menu-update',
                       ),
                       url(
                           r'^menu/(?P<pk>\d+)/detalle/$',
                           MenuDetailView.as_view(),
                           name='menu-detail',
                       ),
                       url(
                           r'^menu/eliminar/$',
                           'config.views.MenuEliminarView',
                           name='menu-delete',
                       ),
                       url(
                           r'^menu/(?P<pk>\d+)/eliminar/$',
                           'config.views.MenuEliminarByPkView',
                           name='menu-delete-pk',
                       ),
                       url(
                           r'^menuGroup/$',
                           MenuGroupListView.as_view(),
                           name='menu-group-list',
                       ),

                       url(
                           r'^menuGroup/nuevo$',
                           MenuGroupCreateView.as_view(),
                           name='menu-group-create',
                       ),
                       url(
                           r'^menuGroup/(?P<pk>\d+)/editar/$',
                           MenuGroupUpdateView.as_view(),
                           name='menu-group-update',
                       ),

                       url(
                           r'^menuGroup/eliminar/$',
                           'config.views.MenuGroupEliminarView',
                           name='menu-group-delete',
                       ),
                       url(
                           r'^menuGroup/(?P<pk>\d+)/eliminar/$',
                           'config.views.MenuGroupEliminarByPkView',
                           name='menu-group-delete-pk',
                       ),
                       url(
                           r'^obtenerDetalleOrdenEgreso/$',
                           'config.views.obtenerDetalleOrdenEgreso',
                           name='obtener-detalle-orden-egreso',
                       ),
                       url(
                           r'^despacharDetalleOrdenEgreso/$',
                           'config.views.despacharDetalleOrdenEgreso',
                           name='despachar-detalle-orden-egreso',
                       ),
                       url(
                           r'^obtenerOrdenEgreso/$',
                           'config.views.obtenerOrdenEgreso',
                           name='obtener-orden-egreso',
                       ),
                       url(
                           r'^obtenerOrdenEgresoDetalleUnico/$',
                           'config.views.obtenerOrdenEgresoDetalleUnico',
                           name='obtener-orden-egreso-detalle-unico',
                       ),
                       url(
                           r'^eliminarEgreso/$',
                           'config.views.eliminarEgreso',
                           name='eliminar-egreso-automatico',
                       ),
                       url(
                           r'^obtenerDetalleProforma/$',
                           'config.views.obtenerDetalleProforma',
                           name='obtener-detalle-proforma',
                       ),
                       url(
                           r'^obtenerDetallePedido/$',
                           'config.views.obtenerDetallePedido',
                           name='obtener-detalle-pedido',
                       ),
                       url(
                           r'^obtenerCliente/$',
                           'config.views.obtenerCliente',
                           name='obtener-cliente',
                       ),

                       url(
                           r'^obtenerDetalleOrdenIngreso/$',
                           'config.views.obtenerDetalleOrdenIngreso',
                           name='obtener-detalle-orden-ingreso',
                       ),

                       url(
                           r'^tipolugar/$',
                           TipoLugarListView.as_view(),
                           name='tipolugar-list',
                       ),

                       url(
                           r'^tipolugar/nuevo$',
                           TipoLugarCreateView.as_view(),
                           name='tipolugar-create',
                       ),
                       url(
                           r'^tipolugar/(?P<pk>\d+)/editar/$',
                           TipoLugarUpdateView.as_view(),
                           name='tipolugar-update',
                       ),
                       url(
                           r'^tipolugar/(?P<pk>\d+)/detalle/$',
                           TipoLugarDetailView.as_view(),
                           name='tipolugar-detail',
                       ),
                       url(
                           r'^tipolugar/eliminar/$',
                           'config.views.TipoLugarEliminarView',
                           name='tipolugar-delete',
                       ),
                       url(
                           r'^tipolugar/(?P<pk>\d+)/eliminar/$',
                           'config.views.TipoLugarEliminarByPkView',
                           name='tipolugar-delete-pk',
                       ),
                       url(
                           r'^obtenerPedidoOrdenProduccion/$',
                           'config.views.obtenerPedidoOrdenProduccion',
                           name='obtener-pedidoorden',
                       ),

                       url(
                           r'^puntosventa/$',
                           'config.views.PuntosVentaListView',
                           name='puntosventa-list',
                       ),

                       url(
                           r'^puntosventa/nuevo$',
                           PuntosVentaCreateView.as_view(),
                           name='puntosventa-create',
                       ),
                       url(
                           r'^puntosventa/(?P<pk>\d+)/editar/$',
                           PuntosVentaUpdateView.as_view(),
                           name='puntosventa-update',
                       ),
                       url(
                           r'^puntosventa/(?P<pk>\d+)/detalle/$',
                           PuntosVentaDetailView.as_view(),
                           name='puntosventa-detail',
                       ),
                       url(
                           r'^puntosventa/eliminar/$',
                           'config.views.PuntosVentaEliminarView',
                           name='puntosventa-delete',
                       ),
                       url(
                           r'^puntosventa/(?P<pk>\d+)/eliminar/$',
                           'config.views.PuntosVentaEliminarByPkView',
                           name='puntosventa-delete-pk',
                       ),
                       url(
                           r'^parametros/$',
                           'config.views.ParametrosListView',
                           name='parametros-list',
                       ),

                       url(
                           r'^parametros/(?P<pk>\d+)/editar/$',
                           ParametrosUpdateView.as_view(),
                           name='parametros-update',
                       ),
                       url(
                           r'^parametros/new$',
                           'config.views.ParametrosNuevoView',
                           name='parametros-nuevo',
                       ),

                       url(
                           r'^ciudad/$',
                           'config.views.CiudadListView',
                           name='ciudad-list',
                       ),

                       url(
                           r'^ciudad/nuevo$',
                           CiudadCreateView.as_view(),

                           name='ciudad-create',
                       ),
                       url(
                           r'^ciudad/(?P<pk>\d+)/editar/$',
                           CiudadUpdateView.as_view(),
                           name='ciudad-update',
                       ),
                       url(
                           r'^estado_civil/$',
                           'config.views.EstadoCivilListView',
                           name='estado-civil-list',
                       ),

                       url(
                           r'^estado_civil/nuevo$',
                           EstadoCivilCreateView.as_view(),

                           name='estado-civil-create',
                       ),
                       url(
                           r'^estado_civil/(?P<pk>\d+)/editar/$',
                           EstadoCivilUpdateView.as_view(),
                           name='estado-civil-update',
                       ),
                       url(
                           r'^pais/$',
                           'config.views.PaisListView',
                           name='pais-list',
                       ),

                       url(
                           r'^pais/nuevo$',
                           PaisCreateView.as_view(),

                           name='pais-create',
                       ),
                       url(
                           r'^pais/(?P<pk>\d+)/editar/$',
                           PaisUpdateView.as_view(),
                           name='pais-update',
                       ),

                       url(
                           r'^provincia/$',
                           'config.views.ProvinciaListView',
                           name='provincia-list',
                       ),

                       url(
                           r'^provincia/nuevo$',
                           ProvinciaCreateView.as_view(),

                           name='provincia-create',
                       ),
                       url(
                           r'^provincia/(?P<pk>\d+)/editar/$',
                           ProvinciaUpdateView.as_view(),
                           name='provincia-update',
                       ),

                       url(
                           r'^relacion_laboral/$',
                           'config.views.RelacionLaboralListView',
                           name='relacion-laboral-list',
                       ),

                       url(
                           r'^relacion_laboral/nuevo$',
                           RelacionLaboralCreateView.as_view(),

                           name='relacion-laboral-create',
                       ),
                       url(
                           r'^relacion_laboral/(?P<pk>\d+)/editar/$',
                           RelacionLaboralUpdateView.as_view(),
                           name='relacion-laboral-update',
                       ),

                       url(
                           r'^tipo_remuneracion/$',
                           'config.views.TipoRemuneracionListView',
                           name='tipo-remuneracion-list',
                       ),

                       url(
                           r'^tipo_remuneracion/nuevo$',
                           TipoRemuneracionCreateView.as_view(),

                           name='tipo-remuneracion-create',
                       ),
                       url(
                           r'^tipo_remuneracion/(?P<pk>\d+)/editar/$',
                           TipoRemuneracionUpdateView.as_view(),
                           name='tipo-remuneracion-update',
                       ),

                       url(
                           r'^forma_pago_empleado/$',
                           'config.views.FormaPagoEmpleadoListView',
                           name='forma-pago-empleado-list',
                       ),

                       url(
                           r'^forma_pago_empleado/nuevo$',
                           FormaPagoEmpleadoCreateView.as_view(),

                           name='forma-pago-empleado-create',
                       ),
                       url(
                           r'^forma_pago_empleado/(?P<pk>\d+)/editar/$',
                           FormaPagoEmpleadoUpdateView.as_view(),
                           name='forma-pago-empleado-update',
                       ),

                        url(
                           r'^anio/$',
                           'config.views.AnioListView',
                           name='anio-list',
                       ),

                       url(
                           r'^anio/nuevo$',
                           AnioCreateView.as_view(),

                           name='anio-create',
                       ),
                       url(
                           r'^anio/(?P<pk>\d+)/editar/$',
                           AnioUpdateView.as_view(),
                           name='anio-update',
                       ),
                       
                       url(
                           r'^bloqueo_periodo/$',
                           'config.views.BloqueoPeriodoListView',
                           name='bloqueo-periodo-list',
                       ),

                       url(
                           r'^bloqueo_periodo/nuevo$',
                           'config.views.BloqueoPeriodoCreateView',

                           name='bloqueo-periodo-create',
                       ),
                       url(
                           r'^bloqueo_periodo/(?P<pk>\d+)/editar/$',
                           BloqueoPeriodoUpdateView.as_view(),
                           name='bloqueo-periodo-update',
                       ),
                       
                       url(
                           r'^bloqueo_periodo/(?P<pk>\d+)/eliminar/$',
                           'config.views.eliminarBloqueoPeriodo',
                           name='bloqueo-periodo-delete-pk',
                       ),

                       )
